apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: gateway
  name: gateway
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gateway
    spec:
      containers:
      - env:
        - name: EXTERNAL_IPS
          value: 35.193.46.59,35.224.65.55,35.194.59.102
        - name: SK_USERID
          value: testid
        - name: SK_API
          value: 35.188.15.7:8080
        - name: K8S_CLUSTERID
          value: newcluster
        - name: K8S_USERNAME
          value: admin
        - name: K8S_PASSWORD
          value: admin2
        image: superkomputer/gateway
        imagePullPolicy: Always
        name: gateway
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: k8s-config
          mountPath: /root/.kube/config
      volumes:
        - name: k8s-config
          hostPath: 
            path: /root/.kube/config
            type: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}