apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://35.225.177.24
  name: cluster
contexts:
- context:
    cluster: cluster
    namespace: default
    user: admin
  name: cluster
current-context: cluster
kind: Config
preferences: {}
users:
- name: cluster
  user:
    password:  
    username: admin
